---
title: "Factor models with Principal Component methods: Strengths and weaknesses"
subtitle: "Project for the course Computational Statistics, University of Bonn 2022"
author: "Krasimira Kirilova"
date: "August 23, 2022"
output: 
  pdf_document:
    toc: true
    number_sections: true
---

# Introduction
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library("pls") # PCA and PLS regression
library("readxl") # read Excel files
library("MASS")
library("esquisse") # addin for data visualization
library("xts") #time series conversion
library("zoo") # time series
library("hornpa") # test how many PCA factors to use in analysis
```
# Simulation
```{r, results='hide', echo=TRUE, message=FALSE}
source("./functions/data_utils.R")
# Load Data set
load(file = "../data/data/WORKING_DATA.rda")

# CONSTANTS ----

# Variables to forecast:
# CPI inflation
# (aggregate) industrial production, 
# (aggregate) unemployment rate
# (effective) federal funds rate
predictor_variables <- c("CPIAUCSL", "IPS10", "LHUR", "FYFF")

# END CONSTANTS ----

# Get data set end date(Note: this could be a constant, but again if you change the file now including later years this code will work automatically)
data_end_date <- tail(zoo::as.Date(WORKING_DATA$rawdata), n = 1)
transformed_ts <- get_transformed_time_series(WORKING_DATA, enddate = data_end_date)

ts_cor <- cor(WORKING_DATA$rawdata)
# Try do to PCA on the whole dataset, all components
set.seed(2)
# prediction_var <- transformed_ts[, predictor_variables]
# transformed_ts <- remove_columns(transformed_ts, predictor_variables)
# result <- pcr(prediction_var ~ ., data = transformed_ts, scale = TRUE, validaiton = CV)
# summary(result)
# validationplot(result, val.type = "MSEP")

IPS10_pca <- pcr(IPS10 ~ ., data = transformed_ts, scale = TRUE, validation = "CV", ncomp = 5)

summary(IPS10_pca)
plot(
  IPS10_pca$scores[, 4], 
  transformed_ts[, "IPS10"][1:190],
  xlab = "PC comp 4 scores",
  ylab = "IPS10")
plot(
  IPS10_pca$scores[, 2], 
  transformed_ts[, "IPS10"][1:190],
  xlab = "PC comp 2 scores",
  ylab = "IPS10")
biplot(IPS10_pca, which = "loadings")
# Shows cross-validated error
plot(RMSEP(IPS10_pca), legendpos = "topright")
# Shows cross-validated predictions vs measured
plot(IPS10_pca, ncomp = 2, asp = 1, line = TRUE)

plot(IPS10_pca, "loadings", comps = 1:3, legendpos = "topleft", xlab = "nm")
abline(h = 0)

```